CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "guid" varchar UNIQUE PRIMARY KEY NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role_guid" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by" varchar NOT NULL DEFAULT 'system',
  "updated_at" timestamp,
  "updated_by" varchar
);
INSERT INTO users (guid, email, password, role_guid)
VALUES (
    gen_random_uuid(),
    'super1@gmail.com',
    '$2a$12$LQi1CpKB/dUNMKko2sHd/.umM9hdOYSoMRF7b8JbgiV3ZvSWIEqQC',
    (
      SELECT guid
      FROM roles
      WHERE name = 'Super Admin'
    )
  ),
  (
    gen_random_uuid(),
    'admin@gmail.com',
    '$2a$12$LQi1CpKB/dUNMKko2sHd/.umM9hdOYSoMRF7b8JbgiV3ZvSWIEqQC',
    (
      SELECT guid
      FROM roles
      WHERE name = 'Admin'
    )
  ) ON CONFLICT DO NOTHING;